-- ═══════════════════════════════════════════════════════════════════════════
-- QUARANTINE COMPLETE TEST — Manual + SP Auto-Reprocess (Consolidated)
-- ═══════════════════════════════════════════════════════════════════════════
-- TABLE: NEW_TEST.QUARANTINE.RAW_VEEVA_CRM_CALLS_REJECTED
--
-- PART A: Manual quarantine flow (step-by-step visibility)
-- PART B: SP-driven auto-reprocess (production flow)
--
-- RUN EACH STEP SEQUENTIALLY
-- ═══════════════════════════════════════════════════════════════════════════


-- ═══════════════════════════════════════════════════════════════════════════
--                    PART A — MANUAL QUARANTINE FLOW
-- ═══════════════════════════════════════════════════════════════════════════


-- ─────────────────────────────────────────────────────────────────────────
-- STEP 1: CLEANUP
-- ─────────────────────────────────────────────────────────────────────────

DELETE FROM NEW_TEST.QUARANTINE.RAW_VEEVA_CRM_CALLS_REJECTED WHERE RUN_ID LIKE 'QTEST%';
DELETE FROM NEW_TEST.BRONZE.RAW_VEEVA_CRM_CALLS WHERE _AUDIT_RUN_ID IN ('QTEST_BRONZE', 'QTEST_REPROCESSED');
SELECT _AUDIT_RUN_ID FROM NEW_TEST.BRONZE.RAW_VEEVA_CRM_CALLS


-- ─────────────────────────────────────────────────────────────────────────
-- STEP 2: INSERT BAD + GOOD DATA INTO BRONZE
-- ─────────────────────────────────────────────────────────────────────────
// FOR TEETSING IM DROPPING THE NOT NULL 
ALTER TABLE NEW_TEST.BRONZE.RAW_VEEVA_CRM_CALLS ALTER COLUMN NPI DROP NOT NULL;

SELECT * FROM NEW_TEST.BRONZE.RAW_VEEVA_CRM_CALLS 
WHERE CALL_ID LIKE 'QTEST%'
ORDER BY _AUDIT_CREATED_AT

INSERT INTO NEW_TEST.BRONZE.RAW_VEEVA_CRM_CALLS
(CALL_ID, NPI, CALL_DATE, TERRITORY_CODE, REP_ID, _AUDIT_IS_DELETED, _AUDIT_LOAD_TS, _AUDIT_RUN_ID)
SELECT
  'QTEST_NULL_' || SEQ4()::VARCHAR, NULL, CURRENT_DATE(),
  'TERR_001', 'REP_100', FALSE, CURRENT_TIMESTAMP(), 'QTEST_BRONZE'
FROM TABLE(GENERATOR(ROWCOUNT => 5));

INSERT INTO NEW_TEST.BRONZE.RAW_VEEVA_CRM_CALLS
(CALL_ID, NPI, CALL_DATE, TERRITORY_CODE, REP_ID, _AUDIT_IS_DELETED, _AUDIT_LOAD_TS, _AUDIT_RUN_ID)
VALUES
('QTEST_BAD_1', 'ABC123',     CURRENT_DATE(), 'TERR_001', 'REP_100', FALSE, CURRENT_TIMESTAMP(), 'QTEST_BRONZE'),
('QTEST_BAD_2', '12345',      CURRENT_DATE(), 'TERR_001', 'REP_100', FALSE, CURRENT_TIMESTAMP(), 'QTEST_BRONZE'),
('QTEST_BAD_3', '99-INVALID', CURRENT_DATE(), 'TERR_001', 'REP_100', FALSE, CURRENT_TIMESTAMP(), 'QTEST_BRONZE');

INSERT INTO NEW_TEST.BRONZE.RAW_VEEVA_CRM_CALLS
(CALL_ID, NPI, CALL_DATE, TERRITORY_CODE, REP_ID, _AUDIT_IS_DELETED, _AUDIT_LOAD_TS, _AUDIT_RUN_ID)
VALUES
('QTEST_GOOD_1', '1234567890', CURRENT_DATE(), 'TERR_001', 'REP_100', FALSE, CURRENT_TIMESTAMP(), 'QTEST_BRONZE'),
('QTEST_GOOD_2', '1234567891', CURRENT_DATE(), 'TERR_001', 'REP_101', FALSE, CURRENT_TIMESTAMP(), 'QTEST_BRONZE'),
('QTEST_GOOD_3', '1234567892', CURRENT_DATE(), 'TERR_002', 'REP_102', FALSE, CURRENT_TIMESTAMP(), 'QTEST_BRONZE'),
('QTEST_GOOD_4', '1234567893', CURRENT_DATE(), 'TERR_002', 'REP_103', FALSE, CURRENT_TIMESTAMP(), 'QTEST_BRONZE'),
('QTEST_GOOD_5', '1234567894', CURRENT_DATE(), 'TERR_003', 'REP_104', FALSE, CURRENT_TIMESTAMP(), 'QTEST_BRONZE');


-- ─────────────────────────────────────────────────────────────────────────
-- STEP 3: VERIFY BRONZE — 13 rows (5 null + 3 bad format + 5 good)
-- ─────────────────────────────────────────────────────────────────────────

SELECT CALL_ID, NPI, TERRITORY_CODE,
  CASE WHEN NPI IS NULL THEN 'NULL NPI → QUARANTINE'
       WHEN NOT REGEXP_LIKE(NPI, '^[0-9]{10}$') THEN 'BAD FORMAT → QUARANTINE'
       ELSE 'GOOD → PASS'
  END AS expected_outcome
FROM NEW_TEST.BRONZE.RAW_VEEVA_CRM_CALLS
WHERE _AUDIT_RUN_ID = 'QTEST_BRONZE'
ORDER BY expected_outcome;


-- ─────────────────────────────────────────────────────────────────────────
-- STEP 4: SIMULATE QUARANTINE — Move bad rows to quarantine table
-- ─────────────────────────────────────────────────────────────────────────

INSERT INTO NEW_TEST.QUARANTINE.RAW_VEEVA_CRM_CALLS_REJECTED
(CALL_ID, NPI, CALL_DATE, TERRITORY_CODE, REP_ID, _AUDIT_IS_DELETED, _AUDIT_LOAD_TS,
 _AUDIT_RUN_ID, _AUDIT_ENV, QUARANTINE_REASON, QUARANTINE_RULE_CODE, QUARANTINE_SEVERITY,
 BATCH_ID, RUN_ID, QUARANTINE_STATUS)
SELECT CALL_ID, NPI, CALL_DATE, TERRITORY_CODE, REP_ID, _AUDIT_IS_DELETED, _AUDIT_LOAD_TS,
  _AUDIT_RUN_ID, 'DEV',
  CASE WHEN NPI IS NULL THEN 'NPI is NULL — mandatory field'
       ELSE 'NPI format invalid — must be 10-digit numeric'
  END,
  CASE WHEN NPI IS NULL THEN 'HCP_NPI_NOT_NULL' ELSE 'HCP_NPI_FORMAT' END,
  CASE WHEN NPI IS NULL THEN 'CRITICAL' ELSE 'HIGH' END,
  'QTEST_BATCH', 'QTEST_RUN_1', 'PENDING'
FROM NEW_TEST.BRONZE.RAW_VEEVA_CRM_CALLS
WHERE _AUDIT_RUN_ID = 'QTEST_BRONZE'
  AND (NPI IS NULL OR NOT REGEXP_LIKE(NPI, '^[0-9]{10}$'));


-- ─────────────────────────────────────────────────────────────────────────
-- STEP 5: VERIFY QUARANTINE — 8 rows PENDING
-- ─────────────────────────────────────────────────────────────────────────

SELECT QUARANTINE_STATUS, QUARANTINE_RULE_CODE, QUARANTINE_SEVERITY, COUNT(*) AS row_count
FROM NEW_TEST.QUARANTINE.RAW_VEEVA_CRM_CALLS_REJECTED
WHERE RUN_ID = 'QTEST_RUN_1'
GROUP BY 1, 2, 3
ORDER BY 2;

SELECT QUARANTINE_ID, CALL_ID, NPI, QUARANTINE_REASON, QUARANTINE_RULE_CODE,
       QUARANTINE_STATUS, QUARANTINED_AT
FROM NEW_TEST.QUARANTINE.RAW_VEEVA_CRM_CALLS_REJECTED
WHERE RUN_ID = 'QTEST_RUN_1'
ORDER BY QUARANTINE_RULE_CODE, CALL_ID;


-- ─────────────────────────────────────────────────────────────────────────
-- STEP 6: FIX DATA — Manual correction (simulates upstream fix)
-- ─────────────────────────────────────────────────────────────────────────

UPDATE NEW_TEST.QUARANTINE.RAW_VEEVA_CRM_CALLS_REJECTED
SET NPI = '9990000001'
WHERE QUARANTINE_STATUS = 'PENDING' AND QUARANTINE_RULE_CODE = 'HCP_NPI_NOT_NULL' AND CALL_ID = 'QTEST_NULL_0';

UPDATE NEW_TEST.QUARANTINE.RAW_VEEVA_CRM_CALLS_REJECTED
SET NPI = '9990000002'
WHERE QUARANTINE_STATUS = 'PENDING' AND QUARANTINE_RULE_CODE = 'HCP_NPI_NOT_NULL' AND CALL_ID = 'QTEST_NULL_1';

UPDATE NEW_TEST.QUARANTINE.RAW_VEEVA_CRM_CALLS_REJECTED
SET NPI = '9990000003'
WHERE QUARANTINE_STATUS = 'PENDING' AND QUARANTINE_RULE_CODE = 'HCP_NPI_NOT_NULL' AND CALL_ID = 'QTEST_NULL_2';

UPDATE NEW_TEST.QUARANTINE.RAW_VEEVA_CRM_CALLS_REJECTED
SET NPI = '9990000004'
WHERE QUARANTINE_STATUS = 'PENDING' AND QUARANTINE_RULE_CODE = 'HCP_NPI_NOT_NULL' AND CALL_ID = 'QTEST_NULL_3';

UPDATE NEW_TEST.QUARANTINE.RAW_VEEVA_CRM_CALLS_REJECTED
SET NPI = '9990000005'
WHERE QUARANTINE_STATUS = 'PENDING' AND QUARANTINE_RULE_CODE = 'HCP_NPI_NOT_NULL' AND CALL_ID = 'QTEST_NULL_4';

UPDATE NEW_TEST.QUARANTINE.RAW_VEEVA_CRM_CALLS_REJECTED
SET NPI = '8880000001'
WHERE QUARANTINE_STATUS = 'PENDING' AND QUARANTINE_RULE_CODE = 'HCP_NPI_FORMAT' AND CALL_ID = 'QTEST_BAD_1';

UPDATE NEW_TEST.QUARANTINE.RAW_VEEVA_CRM_CALLS_REJECTED
SET NPI = '8880000002'
WHERE QUARANTINE_STATUS = 'PENDING' AND QUARANTINE_RULE_CODE = 'HCP_NPI_FORMAT' AND CALL_ID = 'QTEST_BAD_2';

UPDATE NEW_TEST.QUARANTINE.RAW_VEEVA_CRM_CALLS_REJECTED
SET NPI = '8880000003'
WHERE QUARANTINE_STATUS = 'PENDING' AND QUARANTINE_RULE_CODE = 'HCP_NPI_FORMAT' AND CALL_ID = 'QTEST_BAD_3';

SELECT CALL_ID, NPI, QUARANTINE_REASON, QUARANTINE_STATUS,
  CASE WHEN REGEXP_LIKE(NPI, '^[0-9]{10}$') THEN 'FIXED' ELSE 'STILL BAD' END AS fix_status
FROM NEW_TEST.QUARANTINE.RAW_VEEVA_CRM_CALLS_REJECTED
WHERE RUN_ID = 'QTEST_RUN_1'
ORDER BY CALL_ID;


-- ─────────────────────────────────────────────────────────────────────────
-- STEP 7: MANUAL REPROCESS — Re-validate, push back, cleanup
-- ─────────────────────────────────────────────────────────────────────────

UPDATE NEW_TEST.QUARANTINE.RAW_VEEVA_CRM_CALLS_REJECTED
SET QUARANTINE_STATUS = 'REPROCESSED',
    REPROCESS_ATTEMPTS = REPROCESS_ATTEMPTS + 1,
    LAST_REPROCESS_AT = CURRENT_TIMESTAMP(),
    REPROCESSED_RUN_ID = 'QTEST_REPROCESS_1'
WHERE RUN_ID = 'QTEST_RUN_1'
  AND QUARANTINE_STATUS = 'PENDING'
  AND NPI IS NOT NULL
  AND REGEXP_LIKE(NPI, '^[0-9]{10}$');

UPDATE NEW_TEST.QUARANTINE.RAW_VEEVA_CRM_CALLS_REJECTED
SET QUARANTINE_STATUS = 'RETRY_FAILED',
    REPROCESS_ATTEMPTS = REPROCESS_ATTEMPTS + 1,
    LAST_REPROCESS_AT = CURRENT_TIMESTAMP(),
    REPROCESSED_RUN_ID = 'QTEST_REPROCESS_1'
WHERE RUN_ID = 'QTEST_RUN_1'
  AND QUARANTINE_STATUS = 'PENDING';

INSERT INTO NEW_TEST.BRONZE.RAW_VEEVA_CRM_CALLS
(CALL_ID, NPI, CALL_DATE, TERRITORY_CODE, REP_ID, _AUDIT_IS_DELETED, _AUDIT_LOAD_TS, _AUDIT_RUN_ID)
SELECT CALL_ID, NPI, CALL_DATE, TERRITORY_CODE, REP_ID, _AUDIT_IS_DELETED, CURRENT_TIMESTAMP(), 'QTEST_REPROCESSED'
FROM NEW_TEST.QUARANTINE.RAW_VEEVA_CRM_CALLS_REJECTED
WHERE REPROCESSED_RUN_ID = 'QTEST_REPROCESS_1'
  AND QUARANTINE_STATUS = 'REPROCESSED';

DELETE FROM NEW_TEST.QUARANTINE.RAW_VEEVA_CRM_CALLS_REJECTED
WHERE REPROCESSED_RUN_ID = 'QTEST_REPROCESS_1'
  AND QUARANTINE_STATUS = 'REPROCESSED';


-- ─────────────────────────────────────────────────────────────────────────
-- STEP 8: VERIFY PART A RESULTS
-- ─────────────────────────────────────────────────────────────────────────

SELECT QUARANTINE_STATUS, COUNT(*) AS remaining
FROM NEW_TEST.QUARANTINE.RAW_VEEVA_CRM_CALLS_REJECTED
WHERE RUN_ID = 'QTEST_RUN_1'
GROUP BY 1;

SELECT CALL_ID, NPI, _AUDIT_RUN_ID,
  CASE WHEN _AUDIT_RUN_ID = 'QTEST_REPROCESSED' THEN 'RECOVERED FROM QUARANTINE'
       ELSE 'ORIGINAL GOOD DATA'
  END AS data_source
FROM NEW_TEST.BRONZE.RAW_VEEVA_CRM_CALLS
WHERE _AUDIT_RUN_ID IN ('QTEST_BRONZE', 'QTEST_REPROCESSED')
  AND NPI IS NOT NULL
  AND REGEXP_LIKE(NPI, '^[0-9]{10}$')
ORDER BY data_source, CALL_ID;

SELECT 'PART A COMPLETE' AS status,
  (SELECT COUNT(*) FROM NEW_TEST.BRONZE.RAW_VEEVA_CRM_CALLS WHERE _AUDIT_RUN_ID IN ('QTEST_BRONZE','QTEST_REPROCESSED') AND REGEXP_LIKE(NPI, '^[0-9]{10}$')) AS valid_rows_in_bronze,
  (SELECT COUNT(*) FROM NEW_TEST.QUARANTINE.RAW_VEEVA_CRM_CALLS_REJECTED WHERE RUN_ID = 'QTEST_RUN_1') AS rows_still_in_quarantine;


-- ═══════════════════════════════════════════════════════════════════════════
--                    PART B — SP AUTO-REPROCESS FLOW
-- ═══════════════════════════════════════════════════════════════════════════
-- Same scenario but uses SP_REPROCESS_QUARANTINE (production approach)


-- ────────────────────────────────────────────────────────────────────── ───
-- STEP 9: CLEANUP FOR PART B
-- ─────────────────────────────────────────────────────────────────────────

DELETE FROM NEW_TEST.QUARANTINE.RAW_VEEVA_CRM_CALLS_REJECTED WHERE RUN_ID LIKE 'QDEMO%';
DELETE FROM NEW_TEST.BRONZE.RAW_VEEVA_CRM_CALLS WHERE _AUDIT_RUN_ID IN ('QDEMO_BAD', 'QDEMO_FIXED');


-- ─────────────────────────────────────────────────────────────────────────
-- STEP 10: LOAD BAD DATA (MuleSoft sends bad records)
-- ─────────────────────────────────────────────────────────────────────────

INSERT INTO NEW_TEST.BRONZE.RAW_VEEVA_CRM_CALLS
(CALL_ID, NPI, CALL_DATE, TERRITORY_CODE, REP_ID, _AUDIT_IS_DELETED, _AUDIT_LOAD_TS, _AUDIT_RUN_ID)
VALUES
('QDEMO_001', NULL,          CURRENT_DATE(), 'TERR_A', 'REP_01', FALSE, CURRENT_TIMESTAMP(), 'QDEMO_BAD'),
('QDEMO_002', NULL,          CURRENT_DATE(), 'TERR_A', 'REP_01', FALSE, CURRENT_TIMESTAMP(), 'QDEMO_BAD'),
('QDEMO_003', 'ABCDEF',     CURRENT_DATE(), 'TERR_B', 'REP_02', FALSE, CURRENT_TIMESTAMP(), 'QDEMO_BAD'),
('QDEMO_004', '123',        CURRENT_DATE(), 'TERR_B', 'REP_02', FALSE, CURRENT_TIMESTAMP(), 'QDEMO_BAD'),
('QDEMO_005', '5551234567', CURRENT_DATE(), 'TERR_C', 'REP_03', FALSE, CURRENT_TIMESTAMP(), 'QDEMO_BAD');

SELECT CALL_ID, NPI,
  CASE WHEN NPI IS NULL THEN 'NULL → QUARANTINE'
       WHEN NOT REGEXP_LIKE(NPI, '^[0-9]{10}$') THEN 'BAD FORMAT → QUARANTINE'
       ELSE 'VALID → PASS'
  END AS expected_result
FROM NEW_TEST.BRONZE.RAW_VEEVA_CRM_CALLS
WHERE _AUDIT_RUN_ID = 'QDEMO_BAD'
ORDER BY CALL_ID;


-- ─────────────────────────────────────────────────────────────────────────
-- STEP 11: DQM QUARANTINES BAD ROWS (automatic in production)
-- ─────────────────────────────────────────────────────────────────────────

INSERT INTO NEW_TEST.QUARANTINE.RAW_VEEVA_CRM_CALLS_REJECTED
(CALL_ID, NPI, CALL_DATE, TERRITORY_CODE, REP_ID, _AUDIT_IS_DELETED, _AUDIT_LOAD_TS,
 _AUDIT_RUN_ID, _AUDIT_ENV, QUARANTINE_REASON, QUARANTINE_RULE_CODE, QUARANTINE_SEVERITY,
 BATCH_ID, RUN_ID, QUARANTINE_STATUS)
SELECT CALL_ID, NPI, CALL_DATE, TERRITORY_CODE, REP_ID, _AUDIT_IS_DELETED, _AUDIT_LOAD_TS,
  _AUDIT_RUN_ID, 'DEV',
  CASE WHEN NPI IS NULL THEN 'NPI is NULL — mandatory field'
       ELSE 'NPI format invalid — must be 10-digit numeric'
  END,
  CASE WHEN NPI IS NULL THEN 'HCP_NPI_NOT_NULL' ELSE 'HCP_NPI_FORMAT' END,
  CASE WHEN NPI IS NULL THEN 'CRITICAL' ELSE 'HIGH' END,
  'QDEMO_BATCH', 'QDEMO_RUN_1', 'PENDING'
FROM NEW_TEST.BRONZE.RAW_VEEVA_CRM_CALLS
WHERE _AUDIT_RUN_ID = 'QDEMO_BAD'
  AND (NPI IS NULL OR NOT REGEXP_LIKE(NPI, '^[0-9]{10}$'));

SELECT CALL_ID, NPI, QUARANTINE_REASON, QUARANTINE_RULE_CODE, QUARANTINE_STATUS
FROM NEW_TEST.QUARANTINE.RAW_VEEVA_CRM_CALLS_REJECTED
WHERE RUN_ID = 'QDEMO_RUN_1'
ORDER BY CALL_ID;


-- ─────────────────────────────────────────────────────────────────────────
-- STEP 12: SOURCE SYSTEM FIXES DATA (MuleSoft re-sends corrected records)
-- ─────────────────────────────────────────────────────────────────────────

INSERT INTO NEW_TEST.BRONZE.RAW_VEEVA_CRM_CALLS
(CALL_ID, NPI, CALL_DATE, TERRITORY_CODE, REP_ID, _AUDIT_IS_DELETED, _AUDIT_LOAD_TS, _AUDIT_RUN_ID)
VALUES
('QDEMO_001', '7770000001', CURRENT_DATE(), 'TERR_A', 'REP_01', FALSE, CURRENT_TIMESTAMP(), 'QDEMO_FIXED'),
('QDEMO_002', '7770000002', CURRENT_DATE(), 'TERR_A', 'REP_01', FALSE, CURRENT_TIMESTAMP(), 'QDEMO_FIXED'),
('QDEMO_003', '7770000003', CURRENT_DATE(), 'TERR_B', 'REP_02', FALSE, CURRENT_TIMESTAMP(), 'QDEMO_FIXED'),
('QDEMO_004', '7770000004', CURRENT_DATE(), 'TERR_B', 'REP_02', FALSE, CURRENT_TIMESTAMP(), 'QDEMO_FIXED');

UPDATE NEW_TEST.QUARANTINE.RAW_VEEVA_CRM_CALLS_REJECTED q
SET q.NPI = b.NPI
FROM NEW_TEST.BRONZE.RAW_VEEVA_CRM_CALLS b
WHERE q.CALL_ID = b.CALL_ID
  AND b._AUDIT_RUN_ID = 'QDEMO_FIXED'
  AND q.QUARANTINE_STATUS = 'PENDING';

SELECT CALL_ID, NPI, QUARANTINE_REASON, QUARANTINE_STATUS,
  CASE WHEN REGEXP_LIKE(NPI, '^[0-9]{10}$') THEN 'NOW VALID' ELSE 'STILL INVALID' END AS validation
FROM NEW_TEST.QUARANTINE.RAW_VEEVA_CRM_CALLS_REJECTED
WHERE RUN_ID = 'QDEMO_RUN_1'
ORDER BY CALL_ID;


-- ─────────────────────────────────────────────────────────────────────────
-- STEP 13: AUTO-REPROCESS VIA SP (production method)
-- ─────────────────────────────────────────────────────────────────────────

CALL NEW_TEST.REFERENCE.SP_REPROCESS_QUARANTINE('SP_SILVER_HCP', 'DEV');


-- ─────────────────────────────────────────────────────────────────────────
-- STEP 14: VERIFY PART B RESULTS
-- ─────────────────────────────────────────────────────────────────────────

SELECT QUARANTINE_STATUS, COUNT(*) AS row_count
FROM NEW_TEST.QUARANTINE.RAW_VEEVA_CRM_CALLS_REJECTED
WHERE RUN_ID = 'QDEMO_RUN_1'
GROUP BY 1;

SELECT RUN_ID, PIPELINE_CODE, RUN_STATUS, RUN_TRIGGER_TYPE,
       ROWS_READ, ROWS_INSERTED, DQ_CHECK_STATUS
FROM NEW_TEST.AUDIT.PIPELINE_RUN_LOG
WHERE RUN_TRIGGER_TYPE = 'REPROCESS'
ORDER BY RUN_START_TIME DESC
LIMIT 3;

SELECT
  (SELECT COUNT(*) FROM NEW_TEST.QUARANTINE.RAW_VEEVA_CRM_CALLS_REJECTED WHERE RUN_ID = 'QDEMO_RUN_1' AND QUARANTINE_STATUS = 'PENDING') AS pending,
  (SELECT COUNT(*) FROM NEW_TEST.QUARANTINE.RAW_VEEVA_CRM_CALLS_REJECTED WHERE RUN_ID = 'QDEMO_RUN_1' AND QUARANTINE_STATUS = 'REPROCESSED') AS reprocessed,
  (SELECT COUNT(*) FROM NEW_TEST.QUARANTINE.RAW_VEEVA_CRM_CALLS_REJECTED WHERE RUN_ID = 'QDEMO_RUN_1' AND QUARANTINE_STATUS = 'RETRY_FAILED') AS still_failed;


-- ═══════════════════════════════════════════════════════════════════════════
-- EXPECTED RESULTS SUMMARY
-- ═══════════════════════════════════════════════════════════════════════════
--
-- PART A (Manual):
--   Step 3:  13 rows in Bronze (5 null + 3 bad format + 5 good)
--   Step 5:  8 rows quarantined (PENDING)
--   Step 6:  All 8 fixed with valid NPIs
--   Step 7:  All 8 reprocessed → pushed to Bronze → deleted from quarantine
--   Step 8:  0 in quarantine, 13 valid rows in Bronze
--
-- PART B (SP Auto-Reprocess):
--   Step 10: 5 rows in Bronze (2 null + 2 bad format + 1 good)
--   Step 11: 4 rows quarantined (PENDING)
--   Step 12: Source fixes → quarantine rows updated with valid NPIs
--   Step 13: SP_REPROCESS_QUARANTINE → MERGE back → DELETE from quarantine
--   Step 14: 0 in quarantine, all data recovered
--
-- PRODUCTION FLOW:
--   MuleSoft loads → Pipeline runs → DQM quarantines bad rows →
--   Source fixes → TASK_QUARANTINE_REPROCESS (daily 6AM) auto-reprocesses →
--   Fixed rows flow back to Silver/Gold
--
-- Enable auto-reprocess:
--   ALTER TASK NEW_TEST.REFERENCE.TASK_QUARANTINE_REPROCESS RESUME;
-- ═══════════════════════════════════════════════════════════════════════════

//MY REJECTED TABLE 
-- ═══════════════════════════════════════════════════════════════════════════
-- QUARANTINE TABLE for Veeva CRM Calls — mirrors BRONZE.RAW_VEEVA_CRM_CALLS
-- + quarantine meta columns (needed by 9_Quarantine_Test_Case.sql)
-- ═══════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE TABLE NEW_TEST.QUARANTINE.RAW_VEEVA_CRM_CALLS_REJECTED (
    QUARANTINE_ID           VARCHAR(100)  DEFAULT UUID_STRING(),
    -- ── source columns (mirror BRONZE.RAW_VEEVA_CRM_CALLS) ──
    CALL_ID                 VARCHAR(100),
    NPI                     VARCHAR(10),
    CALL_DATE               DATE,
    PRODUCT_CODE            VARCHAR(20),
    TERRITORY_CODE          VARCHAR(50),
    REP_ID                  VARCHAR(50),
    CALL_TYPE               VARCHAR(30),
    CALL_OUTCOME            VARCHAR(50),
    SAMPLE_UNITS            NUMBER(5,0),
    NOTES                   VARCHAR(2000),
    _AUDIT_RUN_ID           VARCHAR(100),
    _AUDIT_BATCH_ID         VARCHAR(100),
    _AUDIT_LOAD_TS          TIMESTAMP_NTZ,
    _AUDIT_SOURCE_SYSTEM    VARCHAR(50),
    _AUDIT_SOURCE_FILE      VARCHAR(500),
    _AUDIT_ROW_HASH         VARCHAR(64),
    _AUDIT_IS_DELETED       BOOLEAN,
    _AUDIT_ENV              VARCHAR(20),
    _AUDIT_CREATED_AT       TIMESTAMP_NTZ,
    -- ── quarantine meta columns ──
    QUARANTINE_REASON       VARCHAR(1000) NOT NULL,
    QUARANTINE_RULE_CODE    VARCHAR(100)  NOT NULL,
    QUARANTINE_SEVERITY     VARCHAR(20),
    QUARANTINED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    BATCH_ID                VARCHAR(100),
    RUN_ID                  VARCHAR(100),
    QUARANTINE_STATUS       VARCHAR(20)   DEFAULT 'PENDING',
    REPROCESS_ATTEMPTS      NUMBER(5,0)   DEFAULT 0,
    LAST_REPROCESS_AT       TIMESTAMP_NTZ,
    REPROCESSED_RUN_ID      VARCHAR(100)
)
DATA_RETENTION_TIME_IN_DAYS = 90
COMMENT = 'Quarantined Veeva CRM call records — pending review/reprocessing';

ALTER TABLE NEW_TEST.QUARANTINE.RAW_VEEVA_CRM_CALLS_REJECTED
  CLUSTER BY (QUARANTINE_STATUS, QUARANTINED_AT::DATE);

  CALL NEW_TEST.REFERENCE.EXECUTE_WITH_RETRY(
  'SP_SILVER_HCP',
  'DEV',
  'SELECT 1'
);

SELECT RUN_ID, PIPELINE_CODE, RUN_STATUS, RETRY_ATTEMPT, IS_RETRY, RUN_START_TIME
FROM NEW_TEST.AUDIT.PIPELINE_RUN_LOG
WHERE PIPELINE_CODE = 'SP_SILVER_HCP'
ORDER BY CREATED_AT DESC
LIMIT 5;

CALL NEW_TEST.REFERENCE.EXECUTE_WITH_RETRY(
  'SP_SILVER_HCP',
  'DEV',
  'SELECT * FROM NEW_TEST.SILVER.THIS_TABLE_DOES_NOT_EXIST'
);

SELECT RUN_STATUS, ERROR_CODE, ERROR_MESSAGE, RETRY_ATTEMPT, IS_RETRY, CREATED_AT
FROM NEW_TEST.AUDIT.PIPELINE_RUN_LOG
WHERE PIPELINE_CODE = 'SP_SILVER_HCP' AND RUN_STATUS = 'FAILED'
ORDER BY CREATED_AT DESC LIMIT 6;