// Quarantine Framework — Steps
//
// 1. Data lands in Bronze, then the DQM SP triggers — sending the bad
//    records to the quarantine table with status 'PENDING'.
//
// 2. The quarantine data is then corrected in 2 ways:
//    (1) Re-source sending back the good records the next day.
//    (2) Someone editing manually at the quarantine level.
//
// 3. In between, the Reprocess SP runs as per the schedule, daily at a
//    specific time:
//    - It picks the rows with status (PENDING or RETRY_FAILED) and
//      validates them against all the rules.
//    - If passed   - flagged as REPROCESSED -> sent back to Bronze.
//    - Else        - retry attempts +1 (max 3 attempts), then after
//                     - flagged as REJECTED.

//MANNUAL TESTING QURANTINE FRAMEWORK
TRUNCATE TABLE NEW_TEST.BRONZE.RAW_VEEVA_CRM_CALLS;
TRUNCATE TABLE NEW_TEST.QUARANTINE.RAW_VEEVA_CRM_CALLS_REJECTED;

// INSERT 3+2 GOOD+BAD RECORDS FOR TESTING
INSERT INTO NEW_TEST.BRONZE.RAW_VEEVA_CRM_CALLS
(CALL_ID, NPI, CALL_DATE, TERRITORY_CODE, REP_ID, _AUDIT_IS_DELETED, _AUDIT_LOAD_TS, _AUDIT_RUN_ID)
VALUES
('M_001', '1111111111', CURRENT_DATE(), 'TERR_A', 'REP_01', FALSE, CURRENT_TIMESTAMP(), 'MANUAL_RUN'),
('M_002', '2222222222', CURRENT_DATE(), 'TERR_A', 'REP_01', FALSE, CURRENT_TIMESTAMP(), 'MANUAL_RUN'),
('M_003', '3333333333', CURRENT_DATE(), 'TERR_B', 'REP_02', FALSE, CURRENT_TIMESTAMP(), 'MANUAL_RUN'),
('M_004', 'BADNPI01',   CURRENT_DATE(), 'TERR_B', 'REP_02', FALSE, CURRENT_TIMESTAMP(), 'MANUAL_RUN'),
('M_005', '123',        CURRENT_DATE(), 'TERR_C', 'REP_03', FALSE, CURRENT_TIMESTAMP(), 'MANUAL_RUN');

/// CALL DQM SP 
CALL NEW_TEST.REFERENCE.RUN_DQM_CHECKS('VEEVA_CRM_INBOUND', 'MANUAL_RUN_1', 'DEV');

SELECT * FROM NEW_TEST.QUARANTINE.RAW_VEEVA_CRM_CALLS_REJECTED;

SELECT CALL_ID, NPI, QUARANTINE_STATUS, QUARANTINE_RULE_CODE, REPROCESS_ATTEMPTS
FROM NEW_TEST.QUARANTINE.RAW_VEEVA_CRM_CALLS_REJECTED ORDER BY CALL_ID;

// NOW IM UPDATING THE ACTUAL BRONZ WITH 1 GOOD RECORD
UPDATE NEW_TEST.BRONZE.RAW_VEEVA_CRM_CALLS
SET NPI = '4444444444'
WHERE CALL_ID = 'M_004';

SELECT * FROM NEW_TEST.BRONZE.RAW_VEEVA_CRM_CALLS;

//SYNC QURANTINE FROM BRONZE 
UPDATE NEW_TEST.QUARANTINE.RAW_VEEVA_CRM_CALLS_REJECTED q
SET NPI = b.NPI
FROM NEW_TEST.BRONZE.RAW_VEEVA_CRM_CALLS b
WHERE q.CALL_ID = b.CALL_ID
  AND q.QUARANTINE_STATUS = 'PENDING';

  UPDATE NEW_TEST.QUARANTINE.RAW_VEEVA_CRM_CALLS_REJECTED
SET NPI = '9876543210'
WHERE CALL_ID = 'M_004';

//CALLING REPROCESS SP 
CALL NEW_TEST.REFERENCE.SP_REPROCESS_QUARANTINE('VEEVA_CRM_INBOUND', 'DEV');

SELECT * FROM NEW_TEST.QUARANTINE.RAW_VEEVA_CRM_CALLS_REJECTED





-- M_004 should be GONE (promoted+deleted); M_005 should be REJECTED at attempt 3
SELECT CALL_ID, NPI, QUARANTINE_STATUS, REPROCESS_ATTEMPTS
FROM NEW_TEST.QUARANTINE.RAW_VEEVA_CRM_CALLS_REJECTED ORDER BY CALL_ID;

-- M_004 should now be in Bronze with the good NPI 9876543210
SELECT CALL_ID, NPI FROM NEW_TEST.BRONZE.RAW_VEEVA_CRM_CALLS WHERE CALL_ID='M_004';

SELECT * FROM NEW_TEST.BRONZE.RAW_VEEVA_CRM_CALLS;

CALL NEW_TEST.REFERENCE.SP_REPROCESS_QUARANTINE('VEEVA_CRM_INBOUND','DEV');

-----------------------------------------------------------------------
UPDATE NEW_TEST.REFERENCE.PIPELINE_MASTER
SET LOAD_TYPE = 'FULL_REFRESH'
WHERE PIPELINE_CODE = 'VEEVA_CRM_INBOUND';

TRUNCATE TABLE NEW_TEST.BRONZE.RAW_VEEVA_CRM_CALLS;
TRUNCATE TABLE NEW_TEST.QUARANTINE.RAW_VEEVA_CRM_CALLS_REJECTED;

SELECT 'bronze' AS tbl, COUNT(*) FROM NEW_TEST.BRONZE.RAW_VEEVA_CRM_CALLS
UNION ALL
SELECT 'quarantine', COUNT(*) FROM NEW_TEST.QUARANTINE.RAW_VEEVA_CRM_CALLS_REJECTED;

SELECT CALL_ID, NPI, QUARANTINE_RULE_CODE, QUARANTINE_STATUS
FROM NEW_TEST.QUARANTINE.RAW_VEEVA_CRM_CALLS_REJECTED
ORDER BY CALL_ID;

SELECT * FROM NEW_TEST.QUARANTINE.RAW_VEEVA_CRM_CALLS_REJECTED

-- Bronze
SELECT CALL_ID, NPI,
  CASE WHEN REGEXP_LIKE(NPI,'^[0-9]{10}$') THEN 'VALID' ELSE 'BAD' END AS status
FROM NEW_TEST.BRONZE.RAW_VEEVA_CRM_CALLS ORDER BY CALL_ID;

-- Quarantine
SELECT CALL_ID, NPI, QUARANTINE_STATUS FROM NEW_TEST.QUARANTINE.RAW_VEEVA_CRM_CALLS_REJECTED ORDER BY CALL_ID;

UPDATE NEW_TEST.REFERENCE.PIPELINE_MASTER
SET IS_ACTIVE = FALSE
WHERE PIPELINE_CODE LIKE 'VEEVA%'

SELECT PIPELINE_CODE, IS_ACTIVE
FROM NEW_TEST.REFERENCE.PIPELINE_MASTER


